### ISSUE TITLE
Does it work on sub domains ?

### ISSUE THREAD

**Issue by munge83** [synox/disposable-email#2]
Does it work on sub domains ?
I installed but I don't get emails. 
I ollso neaded to delete composer.lock file because I couldn't istall the exorus/php-mime-mail-parser

**Comment by synox** [comment]
yes, it can handle messages to subdomains (e.g. master@munge.server2.example.com). It only compares the part before the @ sign.

**Comment by munge83** [comment]
Do you have any idea why it's not working ?

**Comment by synox** [comment]
make sure you check the php error log. also enable php error reporting with E_ALL. 
if you are having trouble maybe the imap version is easier to install? https://github.com/synox/disposable-email-imap

**Comment by munge83** [comment]
no errors at all in error_log
I insert the error_reporting(E_ALL); and also no errors 

if I run mailparse_msg_create(); nothing happen's , is that ok?

**Comment by synox** [comment]
did you try injecting messages from the command line? that's how i
tested it first.

**Comment by munge83** [comment]
I googled it but can't find how to test it in command line ? Can you help me?

**Comment by synox** [comment]
you have to ssh into your server. then run the input script as the mailserver would. 

create a sample mail (like https://gist.github.com/synox/fa11060975bec7250a46) and save it. then run

```
    cat samplemail.txt | php /path/to/app/pipe_input.php
```

and that should process the mail or return an error. if you don't have SSH access then this solution is possibly not for you. Then https://github.com/synox/disposable-email-imap is easier to configure.

**Comment by munge83** [comment]
I did that and no error was shown in command line. Meaby I'll try that other version
