### ISSUE TITLE
How to install it via cPanel?

### ISSUE THREAD

**Issue by schlos** [synox/disposable-email#3]
I'm having cPanel hositng and since this is php based mail client, how can I install it on server? i.e. what needs to go into public_html and what needs to be outside of public_html folder (if any).

**Comment by synox** [comment]
All goes in public_html. Maybe https://github.com/synox/disposable-email-imap is better for you. 

-- Bitte entschuldigen Sie die Kürze/Formatierung dieser Mail; sie wurde auf dem Smartphone erstellt.

**Comment by schlos** [comment]
Thank you. I've seen both use composer install. How cqn I install
composer while using cPanel file manager of ftp client? I dont have
ssh access on shared web hosting.

## 

Best regards / lijep pozdrav,
Miroslav Schlossberg

**Comment by synox** [comment]
then you can composer locally and upload all the files to the server.
