### ISSUE TITLE
404 not found every load

### ISSUE THREAD

**Issue by overflowwebdesigns** [synox/disposable-email#7]
I have the software installed as you list.  Everything seems to go OK, and then I load up the site and see it auto generates a username and puts it at the end of the URL IE http://1.1.1.1/luepru57/ and then I get a 404.  Seems the code may not be creating the DIR's?  Any ideas?

**Comment by synox** [comment]
It seems you are not running it on apache, or the htaccess file is not beeing interpreted by the apache webserver.

**Comment by overflowwebdesigns** [comment]
Thanks I am past that issue now I seem to be having DB issues I get Slim Application Error:
Type: PDOException
Message: Could not connect to database (?).
File: /var/www/html/vendor/redbeanphp/rb.php
Line: 761

**Comment by synox** [comment]
you must provide more data in order to be helped.

**Comment by overflowwebdesigns** [comment]
Now when I browse to the site I get this output:
http://pastebin.com/a69dqi9u

**Comment by overflowwebdesigns** [comment]
Figured it out I had not apt-get install php5-sqlite

**Comment by synox** [comment]
you might use https://github.com/synox/disposable-email-imap instead, which is easier to install.
