### ISSUE TITLE
Can't receive emails

### ISSUE THREAD

**Issue by stormtrooper42** [synox/disposable-email#8]
Hello, 
i have installed your script but when i try send mails to the temporary mail i receive nothing :/ can you help me ?

King Regards,

**Comment by stormtrooper42** [comment]
This is solved, i have installed postfix and pipe/forward to the file app/pipe_input.php ;)

**Comment by ghost** [comment]
how can i install postfix? and pipe/forward to the file app/pipe_input.php?
Please guide me i install this on my server but email is not receiving :(
