### ISSUE TITLE
Email Not receiving

### ISSUE THREAD

**Issue by ghost** [synox/disposable-email#9]
I installed disposable-email on cpanel but email is not receiving :(
i also forward/pipe email to the php script `app/pipe_input.php`  but email is not receiving
What should i do. Please Guide me

**Comment by synox** [comment]
I am sorry it does not work out of the box. 

make sure you check the php error log. also enable php error reporting with `error_reporting(E_ALL);` in config.php. 

Then also try to run the command manually from the command line: ssh into your server. then run the input script as the mailserver would. 

create a sample mail (like https://gist.github.com/synox/fa11060975bec7250a46) and save it. then run

```
    cat samplemail.txt | php /path/to/app/pipe_input.php
```

and that should process the mail or return an error. if you don't have SSH access then this solution is possibly not for you. Then https://github.com/synox/disposable-mailbox is easier to configure.

EDIT: Copied this guide to https://github.com/synox/disposable-email#troubleshooting

**Comment by ghost** [comment]
if have ssh to my server. i also executed the command nothing is showing.
can you tell me what to do after composer install means how to configure and to receive mail?

**Comment by synox** [comment]
I assume there are not entries in your database after running the pipe_input.php?
It is expected not to return output and just to update the database. 
Maybe check the write permissions for the database.

**Comment by synox** [comment]
Were you able to solve the issue?
